### ISSUE TITLE
The port should also be configurable when using Docker

### ISSUE THREAD

**Issue by PhilWun** [UST-QuAntiL/qhana-plugin-runner#16]
Currently the port gunicorn is listening to is hardcoded to 8080 when using Docker. This should be configurable with an environment variable.
https://github.com/UST-QuAntiL/qhana-plugin-runner/blob/7ac13a21a69df3eae0ad53ce9b5d632d7249ab32/tasks.py#L312

**Comment by buehlefs** [comment]
What is the use case for changing this port? Docker already allows remapping ports so the only place where changing this port has an effect is inside the virtual network of the docker compose setup.
