### ISSUE TITLE
Investigate Issue with mariadb connection

### ISSUE THREAD

**Issue by buehlefs** [UST-QuAntiL/qhana-plugin-runner#29]
Investigate an Issue with mariadb connection using. The issue seems to arise from a bug either in SQLAlchemy or the database driver mysql-connector-python, sqlalchemy and possibly the mariadb version.

Known version ranges wehere the bug can occur:
mysql-connector-python > 8.0.26
sqlalchemy > 1.4.31
mariadb == 1:10.3.34-0ubuntu0.20.04.1

Known version without bugs:
mysql-connector-python == 8.0.26 (and == 8.0.25)
sqlalchemy == 1.4.31
mariadb == 1:10.3.34-0ubuntu0.20.04.1

The bug occurs when creating a new task or updating an existing task. It seems like a transaction fails to write to the database.

Possible mitigations:
- Use another database driver
- Find out which newer versions don't have the bug and upgrade to these versions
- Pin the known working versions
- Find and fix the bug

**Comment by PhilWun** [comment]
Can be closed, as we no longer use mysql-connector-python.
